### PR TITLE
Update inputs

### PR DESCRIPTION
**Pull request by cerati**
input track is now a full track with up to 22 hits, the fit starts at the outer hit and is performed inwards.
a few bugs were fixed along the way.

output:
```
[cerati@lnx7188 p2r-tests]$ ./propagate-tor-test.exe
track in pos: x=-102.947563, y=-36.708145, z=38.196655, r=109.296333, pt=4.547605, phi=-2.936464, theta=1.271765
track in cov: xx=1.17e-06, yy=9.75e-06, zz=6.54e-03
hit in layer=0, pos: x=-102.948914, y=-36.704983, z=45.066959, r=109.296547
hit in layer=1, pos: x=-91.621323, y=-34.184444, z=27.314135, r=97.790810
hit in layer=2, pos: x=-70.587746, y=-28.528856, z=27.315285, r=76.134918
hit in layer=3, pos: x=-66.248306, y=-27.207666, z=27.317106, r=71.617699
hit in layer=4, pos: x=-57.281429, y=-23.916222, z=27.332672, r=62.073727
hit in layer=5, pos: x=-56.728401, y=-24.119436, z=27.315742, r=61.642994
hit in layer=6, pos: x=-46.867657, y=-20.656591, z=14.984816, r=51.217888
hit in layer=7, pos: x=-44.072701, y=-19.622213, z=24.744900, r=48.243488
hit in layer=8, pos: x=-37.148380, y=-16.947161, z=17.419971, r=40.831463
hit in layer=9, pos: x=-36.292278, y=-16.604979, z=17.419371, r=39.910583
hit in layer=10, pos: x=-31.972412, y=-14.884381, z=14.946567, r=35.267265
hit in layer=11, pos: x=-32.206371, y=-14.945889, z=14.864964, r=35.505348
hit in layer=12, pos: x=-25.071812, y=-11.388154, z=7.848724, r=27.536989
hit in layer=13, pos: x=-24.307196, y=-10.998621, z=7.275186, r=26.679758
hit in layer=14, pos: x=-21.185072, y=-10.737291, z=16.653400, r=23.750719
hit in layer=15, pos: x=-24.975006, y=-11.873163, z=7.577486, r=27.653624
hit in layer=16, pos: x=-21.220625, y=-10.212121, z=16.907303, r=23.549997
hit in layer=17, pos: x=-14.189642, y=-6.988428, z=9.277352, r=15.817208
hit in layer=18, pos: x=-9.585781, y=-4.785415, z=7.706897, r=10.713888
hit in layer=19, pos: x=-6.232949, y=-3.137438, z=6.550358, r=6.978049
produce nevts=100 ntrks=9600 smearing by=0.000010
NITER=5
done preparing!
setup time time=5.374000 (s)
done ntracks=4800000 tot time=3.797371 (s) time/trk=7.911190e-07 (s)
formatted 5 100 9600 128 75 3.797371 0 5.374000 1
track x avg=-6.173132 std/avg=0.009910
track y avg=-3.163529 std/avg=0.009324
track z avg=6.510152 std/avg=0.008593
track r avg=6.997734 std/avg=0.003092
track dx/x avg=0.000226 std=0.000674
track dy/y avg=-0.000903 std=0.005086
track dz/z avg=0.000616 std=0.061439
track dr/r avg=-0.000000 std=0.000511
track pt avg=4.549306
track phi avg=-2.671269
track theta avg=1.260787
number of tracks with nans=3
number of tracks failed=35
```

### CODE REVIEW

**Comment by kakwok** [comment]
The PR looks good.
I also measured the performance on CORI GPU nodes. The measurement is pinned to a single socket using all the cores (40 cores in total). 
It's a bit curious that there is not a significant change in the throughput though. 
image

**Comment by cerati** [comment]
Great, thanks Martin. Shall we merge the PR or do we want to wait for the CUDA counterpart?
Thank you for the test, this probably means that the compiler was not smart enough to avoid doing unnecessary computations? Did we ever know for sure that it was the case?

________________________________________

**Comment by kakwok** [comment]
I don't think we need to wait for the CUDA side, but we did see some slow-down when you did the quick fix of the bug:
```
main:                       done ntracks=4800000 tot time=3.569051 (s) time/trk=7.435523e-07 (s)
fix-bugs-trkErr-layer-loop: done ntracks=4800000 tot time=5.455579 (s) time/trk=1.136579e-06 (s)
```
These were some `nan` in the bug-fix version, which prompted us to update the inputs.

**Comment by kakwok** [comment]
Rechecking the performance shows the impact is not as big now:

PR (update-inputs branch):
`done ntracks=4800000 tot time=2.733003 (s) time/trk=5.693756e-07 (s)`
main branch (commit 4f6aa6c6bc3c134664fa2450c7d0ef15ad40ef6a):
`done ntracks=4800000 tot time=2.546961 (s) time/trk=5.306169e-07 (s)`

I think this is good enough record for the PR to be merged.

**Pull request merged**
